# Generated by Django 4.2.1 on 2023-10-24 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dp/')),
                ('application_letter', models.FileField(blank=True, null=True, upload_to='applications/')),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
