# Generated by Django 4.2.1 on 2023-11-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('teacher', 'teacher'), ('student', 'student')], max_length=20, null=True),
        ),
    ]
