# Generated by Django 4.2.1 on 2023-08-31 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0003_remove_teacher_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('qualifications', models.TextField()),
                ('short_description', models.TextField(blank=True)),
                ('sex', models.CharField(max_length=10)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('cv', models.FileField(upload_to='cv/')),
                ('application_letter', models.FileField(upload_to='applications/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
