# Generated by Django 4.2.1 on 2023-08-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_userprofile_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
