# Generated by Django 4.2.1 on 2023-08-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_userprofile_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='application_letter',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
