# Generated by Django 4.2.1 on 2023-10-24 20:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course/')),
                ('class_title', models.CharField(max_length=100)),
                ('max_number_of_student', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('class_description', models.TextField()),
                ('class_duration', models.CharField(max_length=20)),
                ('course_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('class_status', models.CharField(choices=[('Pending', 'Pending'), ('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Ongoing', 'Ongoing')], max_length=100)),
                ('course_material', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.userprofile')),
            ],
        ),
    ]
