# Generated by Django 4.2.1 on 2023-08-07 05:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomacademy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('course_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('HTML & CSS Responsive Web Design', 'HTML & CSS (Responsive Web Design)'), ('Javascript (Interactive Web design)', 'Javascript (Interactive Web design)'), ('Python (Automation)', 'Python (Automation)')], max_length=100),
        ),
    ]
